Sistem pendukung keputusan menemukan rekomendasi perusahaan terbaik untuk investor

Melakukan Import Dependencies yang dibutuhkan

In [37]:
import pandas as pd
import numpy as np

In [38]:
path = "dataset/dataCorporate.csv"
df = pd.read_csv(path)

df.head(5)

,Rating Agency,Corporation,Rating,Rating Date,CIK,Binary Rating,SIC Code,Sector,Ticker,Current Ratio,...,EBITDA Margin,Pre-Tax Profit Margin,Net Profit Margin,Asset Turnover,ROE - Return On Equity,Return On Tangible Equity,ROA - Return On Assets,ROI - Return On Investment,Operating Cash Flow Per Share,Free Cash Flow Per Share
0,Standard & Poor's Ratings Services,American States Water Co.,A-,2010-07-30,1056903,1,4941.0,Utils,AWR,1.1507,...,28.9834,13.6093,8.3224,0.3173,8.1724,8.1978,2.6385,4.4530,1.9957,-0.1333
1,Standard & Poor's Ratings Services,Automatic Data Processing Inc.,AAA,2010-09-16,8670,1,7374.0,BusEq,ADP,1.1129,...,23.9379,20.8699,13.5690,0.3324,22.0354,47.2858,4.4944,21.8765,0.2501,0.3132
2,Standard & Poor's Ratings Services,Avnet Inc.,BBB-,2010-11-23,8858,1,5065.0,Shops,AVT,1.9276,...,3.6338,3.0536,2.1418,2.4620,13.6376,16.7991,5.2731,9.6494,-7.6079,-7.3231
3,Standard & Poor's Ratings Services,California Water Service Co.,AA-,2010-06-29,1035201,1,4941.0,Utils,CWT,0.8358,...,27.9377,15.1135,9.0246,0.2946,9.6412,9.7015,2.6583,5.1018,1.7438,-0.8999
4,Standard & Poor's Ratings Services,Cardinal Health Inc.,A,2010-07-14,721371,1,5122.0,Shops,CAH,1.2931,...,1.5847,1.2304,0.6518,4.9276,11.1256,19.4184,2.9364,8.1844,1.9725,2.4174

Melihat Tipe data untuk setiap kolom di dataset

In [39]:
print(df.dtypes)

Rating Agency                     object
Corporation                       object
Rating                            object
Rating Date                       object
CIK                                int64
Binary Rating                      int64
SIC Code                         float64
Sector                            object
Ticker                            object
Current Ratio                    float64
Long-term Debt / Capital         float64
Debt/Equity Ratio                float64
Gross Margin                     float64
Operating Margin                 float64
EBIT Margin                      float64
EBITDA Margin                    float64
Pre-Tax Profit Margin            float64
Net Profit Margin                float64
Asset Turnover                   float64
ROE - Return On Equity           float64
Return On Tangible Equity        float64
ROA - Return On Assets           float64
ROI - Return On Investment       float64
Operating Cash Flow Per Share    float64
Free Cash Flow Per Share         float64
dtype: object

In [40]:
df.describe()

,CIK,Binary Rating,SIC Code,Current Ratio,Long-term Debt / Capital,Debt/Equity Ratio,Gross Margin,Operating Margin,EBIT Margin,EBITDA Margin,Pre-Tax Profit Margin,Net Profit Margin,Asset Turnover,ROE - Return On Equity,Return On Tangible Equity,ROA - Return On Assets,ROI - Return On Investment,Operating Cash Flow Per Share,Free Cash Flow Per Share
count,7.805000e+03,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000,7805.000000
mean,7.371616e+05,0.653299,4052.576810,1.926313,0.452804,0.177349,42.433909,11.531612,11.582683,20.071493,8.659944,5.995566,0.849843,15.950507,21.481589,4.575705,7.076084,0.479756,0.119491
std,5.143542e+05,0.475950,1870.848802,1.921651,2.629158,34.456334,23.742020,25.469044,25.483934,24.380407,27.866408,24.055577,0.696204,230.592526,462.734075,9.229899,24.382027,6.050626,7.253660
min,1.750000e+03,0.000000,100.000000,0.174900,-86.363600,-1473.098000,-87.684000,-461.787800,-461.787800,-360.816900,-476.010000,-414.824800,0.068400,-11258.210000,-14023.260000,-226.442500,-745.454500,-91.330200,-130.665800
25%,9.355600e+04,0.000000,2834.000000,1.077300,0.286500,0.419700,22.453900,6.098200,6.181100,11.162100,4.008700,2.637100,0.399500,6.022800,-12.233900,2.391900,3.692600,-0.448500,-0.723700
50%,8.795260e+05,1.000000,3714.000000,1.496800,0.427200,0.752800,39.635400,12.120100,12.155800,18.304500,9.705100,6.938900,0.661200,12.500000,10.564100,4.767500,7.440800,0.237800,0.133500
75%,1.091587e+06,1.000000,4931.000000,2.161000,0.542200,1.211600,59.641700,19.464600,19.539900,30.661600,16.676900,12.366700,1.038800,20.515700,26.894100,7.881300,12.515100,1.088800,0.997800
max,1.748790e+06,1.000000,9997.000000,34.076800,171.500000,194.375000,100.000000,93.993000,93.993000,286.493500,221.289400,219.390300,8.503900,7038.461000,9882.979000,114.716900,466.666700,282.192100,107.737700

Dari dataset yang diambil, diputuskan untuk mengambil bebrapa kolom yang bisa dijadikan kriteria untuk sistem pendukung keputusan rekomendasi perusahaan terbaik untuk investor
1. Rating: Memberikan gambaran tentang kualitas kredit dan risiko perusahaan menurut lembaga pemeringkat independen.

2. Debt/Equity Ratio: Menunjukkan struktur modal perusahaan dan tingkat leverage keuangan. Rasio ini penting untuk menilai risiko keuangan perusahaan.

3. Net Profit Margin: Mengukur efisiensi perusahaan dalam menghasilkan laba bersih dari pendapatannya. Ini menunjukkan profitabilitas keseluruhan perusahaan.

4. ROE - Return On Equity: Mengukur seberapa efisien perusahaan menggunakan ekuitas pemegang saham untuk menghasilkan laba. Ini adalah indikator penting bagi investor untuk menilai kinerja manajemen dalam menggunakan modal.

Keempat kriteria ini memberikan gambaran yang cukup komprehensif tentang kesehatan keuangan, risiko, profitabilitas, dan efisiensi manajemen perusahaan, yang sangat relevan bagi investor dalam membuat keputusan investasi.

Dan dari keempat kriteria tersebut telah ditentukan cost dan benefitnya
1. ROE - Return On Equity
   - Benefit: Mengukur efisiensi perusahaan dalam menghasilkan keuntungan dari modal pemegang saham.
   - Nilai yang lebih tinggi menunjukkan perusahaan lebih efisien dalam menggunakan ekuitas untuk menghasilkan laba.

2. Net Profit Margin
   - Benefit: Menunjukkan persentase pendapatan yang tersisa sebagai laba bersih setelah semua biaya dan pajak.
   - Margin yang lebih tinggi menandakan profitabilitas yang lebih baik.

3. Operating Cash Flow Per Share
   - Benefit: Menggambarkan kemampuan perusahaan menghasilkan kas dari operasi bisnisnya per saham.
   - Nilai yang lebih tinggi menunjukkan kinerja operasional yang lebih kuat.

Cost (kriteria yang lebih rendah nilainya lebih baik):

1. Debt/Equity Ratio
   - Cost: Mengukur tingkat leverage keuangan perusahaan.
   - Rasio yang lebih rendah menunjukkan risiko keuangan yang lebih kecil dan struktur modal yang lebih konservatif.

untuk bobot dari setiap kriteria
1. ROE - Return On Equity (Benefit)
   Bobot: 30%
   Alasan: ROE adalah indikator kunci efisiensi perusahaan dalam menghasilkan laba dari modal pemegang saham. Ini sangat penting bagi investor karena langsung menunjukkan tingkat pengembalian investasi mereka.

2. Net Profit Margin (Benefit)
   Bobot: 25%
   Alasan: Net Profit Margin menunjukkan efisiensi operasional dan kemampuan perusahaan menghasilkan laba dari pendapatannya. Ini penting untuk menilai profitabilitas keseluruhan, namun sedikit di bawah ROE dalam hal kepentingan langsung bagi investor.

3. Operating Cash Flow Per Share (Benefit)
   Bobot: 20%
   Alasan: Arus kas operasional adalah indikator penting kesehatan finansial dan kemampuan perusahaan menghasilkan kas dari operasi utamanya. Meski penting, ini diberi bobot lebih rendah karena bisa berfluktuasi lebih banyak dalam jangka pendek.

4. Debt/Equity Ratio (Cost)
   Bobot: 25%
   Alasan: Rasio ini sangat penting untuk menilai risiko finansial perusahaan. Struktur modal yang sehat adalah kunci keberlanjutan jangka panjang, sehingga diberi bobot yang cukup signifikan.

Total bobot: 100%


- Bobot yang lebih tinggi diberikan pada ROE dan Net Profit Margin karena keduanya langsung berkaitan dengan profitabilitas, yang umumnya menjadi fokus utama investor.
- Operating Cash Flow Per Share mendapat bobot sedikit lebih rendah karena, meski penting, arus kas bisa lebih berfluktuasi dan tidak selalu mencerminkan profitabilitas jangka panjang.
- Debt/Equity Ratio mendapat bobot yang cukup signifikan karena risiko finansial sangat penting dalam menilai kesehatan dan keberlanjutan perusahaan.

Data Preparation

Setelah menentukan kriteria dan bobot dari dataset selanjutnya akan dilakukan tahap data preparation

karna kolom kriteria sudah ditentukan, maka kolom yang tidak termasuk kriteria akan didrop/hapus

In [41]:
df = df.loc[:,['Corporation','ROE - Return On Equity','Net Profit Margin','Operating Cash Flow Per Share','Debt/Equity Ratio']];

df.head()

,Corporation,ROE - Return On Equity,Net Profit Margin,Operating Cash Flow Per Share,Debt/Equity Ratio
0,American States Water Co.,8.1724,8.3224,1.9957,0.8847
1,Automatic Data Processing Inc.,22.0354,13.5690,0.2501,0.0073
2,Avnet Inc.,13.6376,2.1418,-7.6079,0.4255
3,California Water Service Co.,9.6412,9.0246,1.7438,0.9491
4,Cardinal Health Inc.,11.1256,0.6518,1.9725,0.4036

meilihat adakah data yang kosong pada dataframe

In [42]:
print(df.isna().sum())

Corporation                      0
ROE - Return On Equity           0
Net Profit Margin                0
Operating Cash Flow Per Share    0
Debt/Equity Ratio                0
dtype: int64

Karna data yang diambil merupakan gabungan data dari bebrapa lembaga survei jadi ada data yang memiliki nilai yang sama, data ini yang harus dibersihkan juga

In [43]:
duplicates_specific = df[df.duplicated(subset=['Corporation'], keep=False)]
print("\nJumlah baris duplikat:", duplicates_specific.shape[0])

Jumlah baris duplikat: 7593

Setelah ditemukan data yang duplicate, bisa dilakuman pembersihan data

In [44]:
df_clean = df.drop_duplicates(subset=['Corporation'])
print(df_clean)

                         Corporation  ROE - Return On Equity  \
0          American States Water Co.                  8.1724
1     Automatic Data Processing Inc.                 22.0354
2                         Avnet Inc.                 13.6376
3       California Water Service Co.                  9.6412
4               Cardinal Health Inc.                 11.1256
...                              ...                     ...
7766                   Welbilt, Inc.                 12.9974
7769         Westlake Chemical Corp.                 18.6697
7784                     Xerox Corp.                  9.7833
7793            YPF Sociedad Anonima                  3.6742
7802       iHeartCommunications Inc.                 11.8335

      Net Profit Margin  Operating Cash Flow Per Share  Debt/Equity Ratio
0                8.3224                         1.9957             0.8847
1               13.5690                         0.2501             0.0073
2                2.1418                        -7.6079             0.4255
3                9.0246                         1.7438             0.9491
4                0.6518                         1.9725             0.4036
...                 ...                            ...                ...
7766            10.0057                        -0.4174             0.0022
7769            14.4074                         0.4307             0.2128
7784             7.9896                        -0.6035             0.6973
7793             2.9327                        -3.0941             0.8779
7802             8.0626                         0.0907             0.1523

[1377 rows x 5 columns]

Selanjutnya data yang sudah dibersihkan akan dimasukkan ke file csv untuk selanjutnya di proses

In [45]:
df_clean.to_csv('dataset/dataset_clean.csv', index=False)